#!/usr/bin/env bash

set  -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=6
account=def-chdesa
save_dir=ACDC_005_CAT_standard_3runs

ratio1=0.05
unlab_ratio1=$(python -c "print(1-${ratio1})")

declare -a StringArray=(
# acdc_005 CAT standard  pertur_eps: [0.00001, 0.001, 0.5, 1, 2]   reg:[0.0001, 0.0003, 0.0005, 0.0007, 0.001, 0.003, 0.005]  cons:[0.00003, 0.00005, 0.00007, 0.0001, 0.0003, 0.0005, 0.0007]
# 401eps_05T
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.00003 RegScheduler.max_value=0.0001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_301reg403cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_301reg405cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.00007 RegScheduler.max_value=0.0001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_301reg407cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_301reg301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_301reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_301reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.00003 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_303reg403cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_303reg301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_303reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_305reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.00007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_307reg407cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_307reg301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_307reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_307reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_201reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.00007 RegScheduler.max_value=0.003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_203reg407cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_203reg301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_203reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.00001 VATsettings.Temperature=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_401eps05T_205reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# 0.001eps
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.001 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_201eps_303reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# 0.5
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg405cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg405cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg405cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.00007 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg407cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.00007 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg407cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.00007 RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg407cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0003 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_303reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# k is means the local constraint

)

for cmd in "${StringArray[@]}"
do
	echo ${cmd}
	CC_wrapper "${time}" "${account}" "${cmd}" 16

done

