#!/usr/bin/env bash

set  -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=6
account=def-chdesa
save_dir=ACDC_005_CAT_ablation_L_0929

ratio1=0.05
unlab_ratio1=$(python -c "print(1-${ratio1})")

declare -a StringArray=(
# acdc_005 CAT standard  pertur_eps: [0.00001, 0.001, 0.5, 1, 2]   reg:[0.0001, 0.0003, 0.0005, 0.0007, 0.001, 0.003, 0.005]  cons:[0.00003, 0.00005, 0.00007, 0.0001, 0.0003, 0.0005, 0.0007]
# 0.5
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_307reg307cons_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg305con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=0.5 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_05eps_305reg307con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"


#1
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_201reg307con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_l3run1  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_l3run2  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_l3run3  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_l5run1  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_l5run2  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303cons_l5run3  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303con_l7run1  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303con_l7run2  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg303con_l7run3  Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_307reg307con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons__l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons__l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons__l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons__l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons__l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons__l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg303cons_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg305con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=1 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_1eps_305reg307con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#2
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#----k
"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.001 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_201reg307con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#------

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg303con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0007 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_307reg305con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0003 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg303con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305con_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305con_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0005 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg305con_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007  RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l3run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l3run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=3 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l3run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l5run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l5run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=5 Constraints.Connectivity.local_conn_Kernel=3 Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l5run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l7run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l7run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=4 Dataset=acdc Foreground=all Trainer.name=consVat VATsettings.pertur_eps=2 ConstraintWeightScheduler.max_value=0.0007 RegScheduler.max_value=0.0005 Constraints.Connectivity.flood_fill_Kernel=7 Constraints.Connectivity.local_conn_Kernel=3  Constraints.Constraint=connectivity Constraints.reward_type=soft Trainer.save_dir=${save_dir}/cat_2eps_305reg307cons_l7run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

)

for cmd in "${StringArray[@]}"
do
	echo ${cmd}
	CC_wrapper "${time}" "${account}" "${cmd}" 16

done

