#!/usr/bin/env bash

set  -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=6
account=def-chdesa
save_dir=20230106_hippocampus_005L_plugin

ratio1=0.05
unlab_ratio1=$(python -c "print(1-${ratio1})")

declare -a StringArray=(

# co-training
#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=0.005 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/cot_205reg_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=0.005 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/cot_205reg_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=0.005 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/cot_205reg_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=0.0005 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/cot_305reg_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=0.0005 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/cot_305reg_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=0.0005 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/cot_305reg_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# Cot + CAT
#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps401cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps401cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg1eps401cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg1eps201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg1eps201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg1eps201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg1eps301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg1eps301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg1eps301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/CoTCAT_305reg1eps401cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/CoTCAT_305reg1eps401cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/CoTCAT_305reg1eps401cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg1eps401cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg1eps401cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=1 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg1eps401cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

##
#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg301eps405cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg301eps405cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.005  Trainer.save_dir=${save_dir}/CoTCAT_205reg301eps405cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps405cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps405cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps405cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps401cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps401cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00001 RegScheduler.max_value=0.001  Trainer.save_dir=${save_dir}/CoTCAT_201reg301eps401cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/CoTCAT_305reg301eps305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/CoTCAT_305reg301eps305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/CoTCAT_305reg301eps305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.001   RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0005  RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.0001  RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps405cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps405cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=cotconsVAT VATsettings.pertur_eps=0.0001 Plugin.mode=cat Constraints.Constraint=connectivity ConstraintWeightScheduler.max_value=0.00005 RegScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/CoTCAT_301reg301eps405cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# MT
#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/MT_2reg_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/MT_2reg_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0 Plugin.mode=vat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0 Trainer.save_dir=${save_dir}/MT_2reg_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# MT + CAT
#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.005   Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_205cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.005   Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.005   Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_405cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_405cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.0001 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/MTVAT_2reg301eps_405cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.005   Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_205cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.005   Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.005   Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.001   Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.001   Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.001   Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0005  Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456  Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345   Arch.num_classes=3 Dataset=hippocampus Optim.lr=0.00001 Trainer.name=MTconsvat VATsettings.pertur_eps=0.1 Plugin.mode=cat RegScheduler.max_value=2 ConstraintWeightScheduler.max_value=0.0001  Trainer.save_dir=${save_dir}/MTVAT_2reg01eps_301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

)

for cmd in "${StringArray[@]}"
do
	echo ${cmd}
	CC_wrapper "${time}" "${account}" "${cmd}" 16

done

