#!/usr/bin/env bash

set  -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=6
account=def-chdesa
save_dir=reward_types

ratio1=0.05
unlab_ratio1=$(python -c "print(1-${ratio1})")

declare -a StringArray=(
# Promise12 same settings but different from the recorded models
#"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.0005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.0005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.0005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.0001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.0001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.0001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary205cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=binary cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_binary205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.0005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.0005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.0005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder205cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py seed=1234567 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=0.4 Credit_type=discretecontinue cons_weight=0.001 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cavat_promise_ladder201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# ACDC                                                                                               
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary205cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.0001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary301cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.0001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary301cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.0001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary301cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.0005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.0005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=binary cons_weight=0.0005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_binary305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.0005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder305cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.0005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder305cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.0005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder305cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder205cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.005 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder201cons_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True  Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder201cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True   Temperature=10 VATeps=2 Credit_type=discretecontinue cons_weight=0.001 RegScheduler.max_value=0.00005 Trainer.save_dir=${save_dir}/cavat_ACDC_ladder201cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

)

for cmd in "${StringArray[@]}"
do
	echo ${cmd}
	CC_wrapper "${time}" "${account}" "${cmd}" 16

done

