#!/usr/bin/env bash

set  -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=6
account=def-chdesa
save_dir=ACDC_0.03

ratio1=0.03
unlab_ratio1=$(python -c "print(1-${ratio1})")

declare -a StringArray=(

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=False Reg_cons=False Temperature=1 Trainer.save_dir=${save_dir}/baseline_f_run1 Data.unlabeled_data_ratio=0.01 Data.labeled_data_ratio=0.99"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=False Reg_cons=False Temperature=1 Trainer.save_dir=${save_dir}/baseline_f_run2 Data.unlabeled_data_ratio=0.01 Data.labeled_data_ratio=0.99"
#"python -O main.py seed=12345 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=False Reg_cons=False Temperature=1 Trainer.save_dir=${save_dir}/baseline_f_run3 Data.unlabeled_data_ratio=0.01 Data.labeled_data_ratio=0.99"

#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=False Reg_cons=False Temperature=1 Trainer.save_dir=${save_dir}/baseline_p_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=False Reg_cons=False Temperature=1 Trainer.save_dir=${save_dir}/baseline_p_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=False Reg_cons=False Temperature=1 Trainer.save_dir=${save_dir}/baseline_p_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# EntMin
#"python -O main.py seed=1234567 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=True Reg_cons=False Temperature=0.5 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/EntMin_301reg05Trun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=True Reg_cons=False Temperature=0.5 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/EntMin_301reg05Trun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Dataset=acdc Foreground=all Optim.lr=0.00001 Trainer.name=Baselines MinEntropy=True Reg_cons=False Temperature=0.5 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/EntMin_301reg05Trun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# VAT
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=False Reg_cons=False Temperature=0.5 VATeps=4 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/vat_301reg1eps05Trun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=False Reg_cons=False Temperature=0.5 VATeps=4 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/vat_301reg1eps05Trun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=False Reg_cons=False Temperature=0.5 VATeps=4 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/vat_301reg1eps05Trun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# CaVAT
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.001 RegScheduler.max_value=0.0005 Trainer.save_dir=${save_dir}/cavatcons_305reg201eps05Trun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.001 RegScheduler.max_value=0.0005 Trainer.save_dir=${save_dir}/cavatcons_305reg201eps05Trun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.001 RegScheduler.max_value=0.0005 Trainer.save_dir=${save_dir}/cavatcons_305reg201eps05Trun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.005 RegScheduler.max_value=0.0005 Trainer.checkpoint_path=runs/${save_dir}/cavatcons_305reg201eps05T205consrun1 Trainer.save_dir=${save_dir}/cavatcons_305reg201eps05T205consrun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.005 RegScheduler.max_value=0.0005  Trainer.checkpoint_path=runs/${save_dir}/cavatcons_305reg201eps05T205consrun2 Trainer.save_dir=${save_dir}/cavatcons_305reg201eps05T205consrun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.005 RegScheduler.max_value=0.0005   Trainer.checkpoint_path=runs/${save_dir}/cavatcons_305reg201eps05T205consrun3 Trainer.save_dir=${save_dir}/cavatcons_305reg201eps05T205consrun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg201eps05T205consrun1 Trainer.save_dir=${save_dir}/cavatcons_301reg201eps05T205consrun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.005 RegScheduler.max_value=0.0001  Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg201eps05T205consrun2 Trainer.save_dir=${save_dir}/cavatcons_301reg201eps05T205consrun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.005 RegScheduler.max_value=0.0001   Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg201eps05T205consrun3 Trainer.save_dir=${save_dir}/cavatcons_301reg201eps05T205consrun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.006 RegScheduler.max_value=0.0001 Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg201eps05T206consrun1 Trainer.save_dir=${save_dir}/cavatcons_301reg201eps05T206consrun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.006 RegScheduler.max_value=0.0001  Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg201eps05T206consrun2 Trainer.save_dir=${save_dir}/cavatcons_301reg201eps05T206consrun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.004 cons_weight=0.006 RegScheduler.max_value=0.0001   Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg201eps05T206consrun3 Trainer.save_dir=${save_dir}/cavatcons_301reg201eps05T206consrun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.00004 cons_weight=0.005 RegScheduler.max_value=0.0001 Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg401eps05T205consrun1 Trainer.save_dir=${save_dir}/cavatcons_301reg401eps05T205consrun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.00004 cons_weight=0.005 RegScheduler.max_value=0.0001  Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg401eps05T205consrun2 Trainer.save_dir=${save_dir}/cavatcons_301reg401eps05T205consrun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.00004 cons_weight=0.005 RegScheduler.max_value=0.0001   Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg401eps05T205consrun3 Trainer.save_dir=${save_dir}/cavatcons_301reg401eps05T205consrun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.00004 cons_weight=0.006 RegScheduler.max_value=0.0001 Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg401eps05T206consrun1 Trainer.save_dir=${save_dir}/cavatcons_301reg401eps05T206consrun1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.00004 cons_weight=0.006 RegScheduler.max_value=0.0001  Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg401eps05T206consrun2 Trainer.save_dir=${save_dir}/cavatcons_301reg401eps05T206consrun2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=consVat Norm_style=L2 VAT_base=True Constraint=True Reg_cons=True Temperature=0.5 VATeps=0.00004 cons_weight=0.006 RegScheduler.max_value=0.0001   Trainer.checkpoint_path=runs/${save_dir}/cavatcons_301reg401eps05T206consrun3 Trainer.save_dir=${save_dir}/cavatcons_301reg401eps05T206consrun3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# co-training
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=cotconsVAT cons_weight=0.001 VATeps=0 Reg_cons=False Temperature=0.5 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cot_prostate_301reg Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=cotconsVAT cons_weight=0.001 VATeps=0 Reg_cons=False Temperature=0.5 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cot_prostate_301reg_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=cotconsVAT cons_weight=0.001 VATeps=0 Reg_cons=False Temperature=0.5 RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cot_prostate_301reg_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#cotCaVAT
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=cotconsVAT cons_weight=0.001 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cotCaVATcons_prostate_301reg_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=cotconsVAT cons_weight=0.001 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cotCaVATcons_prostate_301reg_401eps_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=cotconsVAT cons_weight=0.001 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=0.0001 Trainer.save_dir=${save_dir}/cotCaVATcons_prostate_301reg_401eps_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

# MT
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.001 VATeps=0 Reg_cons=False Temperature=0.5 RegScheduler.max_value=4 Trainer.save_dir=${save_dir}/MT_prostate_4reg_run1 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.001 VATeps=0 Reg_cons=False Temperature=0.5 RegScheduler.max_value=4 Trainer.save_dir=${save_dir}/MT_prostate_4reg_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.001 VATeps=0 Reg_cons=False Temperature=0.5 RegScheduler.max_value=4 Trainer.save_dir=${save_dir}/MT_prostate_4reg_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

#MTCaVAT
#"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.001 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=2 Trainer.save_dir=${save_dir}/MTCaVATcons_2reg_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.001 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=2  Trainer.save_dir=${save_dir}/MTCaVATcons_2reg_401eps_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.001 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=2   Trainer.save_dir=${save_dir}/MTCaVATcons_2reg_401eps_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.005 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=4  Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_401eps205cons  Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_401eps205cons Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.005 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=4   Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_401eps205cons_run2 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_401eps205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.005 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=4    Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_401eps205cons_run3 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_401eps205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.006 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=4  Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_401eps206cons  Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_401eps206cons Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.006 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=4   Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_401eps206cons_run2 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_401eps206cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.006 VATeps=0.00004 Reg_cons=True RegScheduler.max_value=4    Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_401eps206cons_run3 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_401eps206cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.005 VATeps=0.000004 Reg_cons=True RegScheduler.max_value=4  Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_501eps205cons  Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_501eps205cons Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.005 VATeps=0.000004 Reg_cons=True RegScheduler.max_value=4   Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_501eps205cons_run2 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_501eps205cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.005 VATeps=0.000004 Reg_cons=True RegScheduler.max_value=4    Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_501eps205cons_run3 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_501eps205cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py seed=1234567 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.006 VATeps=0.000004 Reg_cons=True RegScheduler.max_value=4  Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_501eps206cons  Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_501eps206cons Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=123456 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.006 VATeps=0.000004 Reg_cons=True RegScheduler.max_value=4   Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_501eps206cons_run2 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_501eps206cons_run2 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py seed=12345 Arch.num_classes=4 Optim.lr=0.00001 Dataset=acdc Foreground=all Trainer.name=MTconsvat cons_weight=0.006 VATeps=0.000004 Reg_cons=True RegScheduler.max_value=4    Trainer.checkpoint_path=runs/${save_dir}/MTCaVATcons_4reg_501eps206cons_run3 Trainer.save_dir=${save_dir}/MTCaVATcons_4reg_501eps206cons_run3 Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"


)

for cmd in "${StringArray[@]}"
do
	echo ${cmd}
	CC_wrapper "${time}" "${account}" "${cmd}" 16

done

