#!/usr/bin/env bash

set  -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=6
account=def-chdesa
save_dir=CaVAT_Xviolate_round2

ratio1=0.05
unlab_ratio1=$(python -c "print(1-${ratio1})")

declare -a StringArray=(

# prostate
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.00004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.00004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=0.00004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=0.00004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.00004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.00004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_401eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.0004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_301eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.0004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_301eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=0.0004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_301eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=0.0004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_301eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.0004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_301eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.0004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_301eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_201eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_201eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=0.004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_201eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=0.004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_201eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_201eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.004 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_201eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.04 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_101eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.04 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_101eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=0.04 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_101eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=0.04 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_101eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.04 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_101eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.04 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_101eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_01eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_01eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
#"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=0.4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_01eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=0.4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_01eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=0.4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_01eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=0.4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_01eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=2 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_05eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=2 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_05eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=2 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_05eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=2 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_05eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=2 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_05eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=2 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_05eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_1eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_1eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_1eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_1eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_1eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=4 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_1eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=8 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_2eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=8 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_2eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=8 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_2eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=8 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_2eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=8 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_2eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=8 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_2eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=16 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_4eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=False VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=16 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VAT_prostate_consU_4eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=False cons_weight=0.001 VATeps=16 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_4eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=False Reg_cons=True  cons_weight=0.001 VATeps=16 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/CAT_prostate_consU_4eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=False cons_weight=0.001 VATeps=16 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_4eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"
"python -O main.py Arch.num_classes=2 Optim.lr=0.00001 Dataset=prostate Trainer.name=consVat Constraint=True  VAT_base=True  Reg_cons=True  cons_weight=0.001 VATeps=16 Temperature=1 RegScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/VCAT_prostate_consU_4eps Data.unlabeled_data_ratio=${unlab_ratio1} Data.labeled_data_ratio=${ratio1}"

)

for cmd in "${StringArray[@]}"
do
	echo ${cmd}
	CC_wrapper "${time}" "${account}" "${cmd}" 16

done

