Arch:
  name: enet
  input_dim: 1
  num_classes: 4  # 2, 3, 4

Optim:
  name: RAdam
  lr: 0.00001

Scheduler:
  name: CosineAnnealingLR
  T_max: 90
  warmup:
    multiplier: 300
    total_epoch: 10

Dataset: acdc # acdc, prostate, spleen, prostateDK
Foreground: all # LV, Myo, RV, all

Data:
  unlabeled_data_ratio: 0.95
  labeled_data_ratio: 0.05
  seed: 12

DataLoader:
  labeled_batch_size: 4
  unlabeled_batch_size: 4
  val_batch_size: 6
  shuffle: True
  num_workers: 0
  pin_memory: False

Trainer:
  name: consVat  # Baselines, NaiveVat, co_training, MeanTeacher, constraintReg, consVat, cotconsVAT, MTconsvat, Pseudolike
  device: cuda
  save_dir: runs
  num_batches: 200
  max_epoch: 100 # 50, 100
  checkpoint_path: runs

RegScheduler:
  begin_epoch: 5 # 5
  max_epoch: 50
  min_value: 0
  max_value: 0

ConstraintWeightScheduler:
  begin_epoch: 10 # 10
  max_epoch: 50
  min_value: 0
  max_value: 0

MinEntropy: False

VATsettings:
  pertur_eps: 0.0001
  Temperature: 1

Constraints:
  examples: adv_examples # adv_examples  original_unlab  both
  Constraint: connectivity  # connectivity, convexity
  num_samples: 5
  reward_type: soft # hard, soft
  reverse_indicator: True # False: FGBG; True: reverse_FGBG
  Connectivity:
    diag_connectivity: 1 # exclude diag
    flood_fill_Kernel: 5
    local_conn_Kernel: 3

Plugin:
  mode: cat # vat cat

seed: 1234567