!!python/object/apply:collections.defaultdict
args:
- !!python/name:ensemble_functions.utils.configManager.%3Clambda%3E ''
dictitems:
  AlphaScheduler:
    begin_epoch: 5
    max_epoch: 50
    max_value: 0.5
    min_value: 0.0
  Arch:
    input_dim: 1
    name: enet
    num_classes: 2
  Constraint: convexity
  Constraints:
    Credit_type: binary
    Reg_cons: true
    Rein_base: false
    VAT_base: false
    cons_connectivity: 1
    cons_weight: 0.001
    num_samples: 10
  Data:
    labeled_data_ratio: 0.05
    seed: 1
    unlabeled_data_ratio: 0.95
  DataLoader:
    labeled_batch_size: 4
    num_workers: 0
    shuffle: true
    unlabeled_batch_size: 4
    val_batch_size: 6
  Dataset: acdc
  Foreground: LV
  Kernel:
    flood_fill: 5
    local_conn: 3
  MinEntropy: false
  Norm_style: L2
  Optim:
    lr: 1.0e-05
    name: RAdam
  RegScheduler:
    begin_epoch: 5
    max_epoch: 50
    max_value: 1.0e-05
    min_value: 0.0
  Scheduler:
    T_max: 90
    name: CosineAnnealingLR
    warmup:
      multiplier: 300
      total_epoch: 10
  SelfPaceScheduler:
    begin_epoch: 5
    max_epoch: 50
    max_value: 6
    min_value: 0.2
  Temperature: 1
  Trainer:
    checkpoint_path: runs
    device: cpu
    max_epoch: 100
    name: convextrainer
    num_batches: 200
    save_dir: runs
  Transform_option: rotate
  VATeps: 0.0001
  lvconvexity:
    Convex_types: defects
  seed: 1234567
