!!python/object/apply:collections.defaultdict
args:
- !!python/name:ensemble_functions.utils.configManager.%3Clambda%3E ''
dictitems:
  Arch:
    input_dim: 1
    name: enet
    num_classes: 2
  ConstraintWeightScheduler:
    begin_epoch: 10
    max_epoch: 50
    max_value: 0
    min_value: 0
  Constraints:
    Connectivity:
      diag_connectivity: 1
      flood_fill_Kernel: 5
      local_conn_Kernel: 3
    Constraint: convexity
    num_samples: 10
    reverse_indicator: true
    reward_type: soft
  Data:
    labeled_data_ratio: 0.05
    seed: 12
    unlabeled_data_ratio: 0.95
  DataLoader:
    labeled_batch_size: 4
    num_workers: 0
    pin_memory: false
    shuffle: true
    unlabeled_batch_size: 4
    val_batch_size: 6
  Dataset: acdc
  Foreground: LV
  MinEntropy: false
  Optim:
    lr: 1.0e-05
    name: RAdam
  RegScheduler:
    begin_epoch: 5
    max_epoch: 50
    max_value: 0
    min_value: 0
  Scheduler:
    T_max: 90
    name: CosineAnnealingLR
    warmup:
      multiplier: 300
      total_epoch: 10
  Trainer:
    checkpoint_path: runs
    device: cpu
    max_epoch: 100
    name: consVat
    num_batches: 200
    save_dir: runs
  VATsettings:
    Temperature: 1
    pertur_eps: 0.0001
  seed: 1234567
